
#include <ros/ros.h>
#include <stdio.h>

#include <image_transport/image_transport.h>
#include <rpwc_msgs/PCloudImageReq.h>
#include <rpwc_msgs/PointCloudImage.h>
#include <rpwc_msgs/cameraInfo.h>
#include <rpwc_msgs/checkHardwareStatus.h>
#include <rpwc_msgs/getSettingsCamera.h>
#include <rpwc_msgs/setSettingsCamera.h>
#include <rpwc_msgs/suggestSettingsCamera.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/PointCloud2.h>

#include <cstdint>
#include <sstream>
#include <string>
#include <vector>

namespace
{
sensor_msgs::PointCloud2::ConstPtr point_cloud_ = boost::make_shared<sensor_msgs::PointCloud2>();
sensor_msgs::Image::ConstPtr image_ = boost::make_shared<sensor_msgs::Image>();
sensor_msgs::CameraInfo::ConstPtr cam_info_ = boost::make_shared<sensor_msgs::CameraInfo>();

bool have_point_cloud_ = false;
bool have_image_ = false;
bool have_camera_info_ = false;

std::string last_settings_path_;
std::string last_preset_name_;
ros::Duration last_suggested_max_capture_time_;
uint8_t last_suggested_ambient_light_frequency_ =
    rpwc_msgs::suggestSettingsCamera::Request::AMBIENT_LIGHT_FREQUENCY_NONE;

std::string quoteYaml(const std::string &value)
{
    std::string escaped;
    escaped.reserve(value.size());
    for(const char ch : value)
    {
        if(ch == '\'')
        {
            escaped += "''";
        }
        else
        {
            escaped += ch;
        }
    }
    return "'" + escaped + "'";
}

std::string buildHardwareStatusInfo()
{
    if(have_image_ && have_point_cloud_ && have_camera_info_)
    {
        return "RealSense bridge ready: image, point cloud and camera info received.";
    }

    std::vector<std::string> missing_topics;
    if(!have_image_)
    {
        missing_topics.push_back("camera/color/image_rect_color");
    }
    if(!have_point_cloud_)
    {
        missing_topics.push_back("camera/depth_registered/points");
    }
    if(!have_camera_info_)
    {
        missing_topics.push_back("camera/color/camera_info");
    }

    std::ostringstream info;
    info << "RealSense bridge waiting for topics: ";
    for(std::size_t i = 0; i < missing_topics.size(); ++i)
    {
        if(i > 0)
        {
            info << ", ";
        }
        info << missing_topics[i];
    }
    return info.str();
}

std::string buildSerializedSettings()
{
    std::ostringstream serialized;
    serialized << "bridge:\n";
    serialized << "  camera_type: realsense\n";
    serialized << "  note: "
               << quoteYaml("Placeholder settings generated by realsense_bridge; no camera settings are applied.")
               << "\n";
    serialized << "  last_requested_preset: " << quoteYaml(last_preset_name_) << "\n";
    serialized << "  last_requested_settings_path: " << quoteYaml(last_settings_path_) << "\n";
    serialized << "  last_suggested_max_capture_time_sec: " << last_suggested_max_capture_time_.toSec() << "\n";
    serialized << "  last_suggested_ambient_light_frequency: "
               << static_cast<int>(last_suggested_ambient_light_frequency_) << "\n";
    return serialized.str();
}
}  // namespace

bool callbackServerCamera(rpwc_msgs::PCloudImageReq::Request &req, rpwc_msgs::PCloudImageReq::Response &res)
{
    (void)req;
    res.data.pointCloud = *point_cloud_;
    res.data.image = *image_;
    return true;
}

bool callbackServerCameraInfo(rpwc_msgs::cameraInfo::Request &req, rpwc_msgs::cameraInfo::Response &res)
{
    (void)req;
    res.cameraInfo = *cam_info_;
    return true;
}

bool callbackServerCheckHardwareStatus(
    rpwc_msgs::checkHardwareStatus::Request &req,
    rpwc_msgs::checkHardwareStatus::Response &res)
{
    (void)req;

    const bool ready = have_image_ && have_point_cloud_ && have_camera_info_;
    res.status.data = ready ? 1 : 0;
    res.result.data = ready;
    res.info.data = buildHardwareStatusInfo();
    return true;
}

bool callbackServerSetSettings(rpwc_msgs::setSettingsCamera::Request &req, rpwc_msgs::setSettingsCamera::Response &res)
{
    last_settings_path_ = req.settingsPath.data;
    res.success.data = true;
    res.info.data =
        "RealSense bridge does not apply settings files; request accepted for RPWC compatibility.";
    ROS_WARN_STREAM("Ignoring set_settings_camera request in RealSense bridge: " << last_settings_path_);
    return true;
}

bool callbackServerSetPreSettings(
    rpwc_msgs::setSettingsCamera::Request &req,
    rpwc_msgs::setSettingsCamera::Response &res)
{
    last_preset_name_ = req.settingsPath.data;
    res.success.data = true;
    res.info.data =
        "RealSense bridge does not apply named presets; request accepted for RPWC compatibility.";
    ROS_WARN_STREAM("Ignoring set_pre_settings_camera request in RealSense bridge: " << last_preset_name_);
    return true;
}

bool callbackServerGetSettings(rpwc_msgs::getSettingsCamera::Request &req, rpwc_msgs::getSettingsCamera::Response &res)
{
    (void)req;
    res.serializedMessage.data = buildSerializedSettings();
    res.success.data = true;
    res.info.data = "RealSense bridge returned placeholder serialized settings for RPWC compatibility.";
    return true;
}

bool callbackServerSuggestSettings(
    rpwc_msgs::suggestSettingsCamera::Request &req,
    rpwc_msgs::suggestSettingsCamera::Response &res)
{
    last_suggested_max_capture_time_ = req.max_capture_time;
    last_suggested_ambient_light_frequency_ = req.ambient_light_frequency;
    res.success.data = true;
    res.info.data =
        "RealSense bridge does not support automatic suggestion of settings; request accepted for RPWC compatibility.";
    ROS_WARN_STREAM(
        "Ignoring suggest_settings_camera request in RealSense bridge. max_capture_time="
        << req.max_capture_time.toSec() << " ambient_light_frequency="
        << static_cast<int>(req.ambient_light_frequency));
    return true;
}

void callback_image(const sensor_msgs::ImageConstPtr &msg)
{
    image_ = msg;
    have_image_ = true;
}

void callback_point_cloud(const sensor_msgs::PointCloud2ConstPtr &cloud_msg)
{
    point_cloud_ = cloud_msg;
    have_point_cloud_ = true;
}

void callback_camera_info(const sensor_msgs::CameraInfoConstPtr &info_msg)
{
    cam_info_ = info_msg;
    have_camera_info_ = true;
}

int main(int argc, char** argv)
{
	//----------------------------------------------------------
	// Preparations
	//----------------------------------------------------------

	// Initialize the node.
	ros::init(argc, argv, "realsense_bridge_node");
	ros::NodeHandle nh;

	ros::ServiceServer serverCheckHardwareStatus =
	    nh.advertiseService("check_hardware_status", callbackServerCheckHardwareStatus);
	ros::ServiceServer serverCamera = nh.advertiseService("sensorMeas", callbackServerCamera);
	ros::ServiceServer serverCameraInfo = nh.advertiseService("camera/info", callbackServerCameraInfo);
	ros::ServiceServer serverSetSettings = nh.advertiseService("set_settings_camera", callbackServerSetSettings);
	ros::ServiceServer serverSetPreSettings =
	    nh.advertiseService("set_pre_settings_camera", callbackServerSetPreSettings);
	ros::ServiceServer serverGetSettings = nh.advertiseService("get_settings_camera", callbackServerGetSettings);
	ros::ServiceServer serverSuggestSettings = nh.advertiseService("suggest_settings_camera", callbackServerSuggestSettings);

    image_transport::ImageTransport it(nh);
	image_transport::Subscriber sub_image = it.subscribe("camera/color/image_rect_color", 1, &callback_image);
    ros::Subscriber sub_point_cloud = nh.subscribe("camera/depth_registered/points", 1, &callback_point_cloud);
    ros::Subscriber sub_camera_info = nh.subscribe("camera/color/camera_info", 1, &callback_camera_info);
	
	ros::spin();

	return 0;
}
